<?php
/**
 * Ugandan cities
 */
global $cities;

$cities['UG'] = array(
        'UG314' => array(
            'Sakodi',
            'Bluetag'
        ),
/**
 * Kampala
 */
        'UG102' => array(
            'Budo',
    'Bugolobi',
    'Bukesa',
    'Bukoto',
    'Bulambiro',
    'Bunga',
    'Buziga',
    'Buye',
    'Bwaise',
    'Bweyogerere',
    'Civic Centre',
    'Gaba',
    'Gayaza',
    'Ggaba',
    'Industrial Area',
    'Kabalagala',
    'Kabowa',
    'Kajjansi',
    'Kampala',
    'Kamwokya',
    'Kansanga',
    'Kasangati',
    'Kasubi',
    'Katanga',
    'Katwe',
    'Katikamu',
    'Kavule',
    'Kawempe',
    'Kazo',
    'Kayanja',
    'Kanyanya',
    'Kibuli',
    'Kigo',
    'Kigowa',
    'Kikoni',
    'Kirombe',
    'Kira',
    'Kireka',
    'Kisaasi',
    'Kisenyi',
    'Kiteezi',
    'Kitende',
    'Kitintale',
    'Kiwatule',
    'Kiwempe',
    'Kololo',
    'Komamboga',
    'Kulambiro',
    'Kyambogo',
    'Kyebando',
    'Kyengera',
    'Kyanja',
    'Lugala',
    'Lubaga',
    'Lubowa',
    'Lubya',
    'Lukuli',
    'Luzira',
    'Lweza',
    'Makerere',
    'Makindye',
    'Matugga',
    'Maya',
    'Mbuya',
    'Mengo',
    'Mpererwe',
    'Mpanga',
    'Munyonyo',
    'Mutundwe',
    'Mutungo',
    'Muyenga',
    'Nabisunsa',
    'Nakasero',
    'Nakawa',
    'Nakulabye',
    'Namirembe',
    'Namungoona',
    'Namuwongo',
    'Nansana',
    'Nateete',
    'Navweru',
    'Nsambya',
    'Nsangi',
    'Ntinda',
    'Ntinda II',
    'Old Kampala',
    'Port Bell',
    'Salaama',
    'Seguku',
    'Spear Motors Zone',
    'Ssisa',
    'Tula',
    'Wamala',
    'Wandegeya',
    'Zzana'
        )
    );